[tool.poetry]
name = "soundcloud-api-client"
version = "2.0.0"
description = "Soundcloud API client"
authors = ["Félix Voituret <contact@mazard-records.com>"]
readme = "README.md"
packages = [
    { include = "soundcloud" },
]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.25.1"
pydantic = "^2.4.2"


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.11.0"
mypy = "^1.7.0"
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.1"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
