name: release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: poetry install --no-root
      - run: poetry build
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
      - run: poetry publish
